### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by the-graduate-student** [the-graduate-student/the-graduate-student.github.io#1]
- [x] The day it all started
- [x] The day I landed on the campus
- [x] The day I met my buddy
- [x] The day I attended my first lecture
- [ ] The day I stopped karate
- [x] The day I went to the library
- [ ] The day I worked in a group
- [ ] The day I asked a question
- [ ] The day I proved by induction
- [ ] The day I had to pee
- [ ] The day I stopped football
- [ ] The day I started CrossFit
- [ ] The day I chose an internship
- [ ] The day I screwed an interview
- [ ] The day I spent the night (db)
- [ ] The day I lost my scholarship
- [ ] The day I graded a homework
- [ ] The day I graded a project
- [ ] The day I graded an exam
- [ ] The day I was a student assistant
- [ ] The day I was a bad student assistant
- [ ] ...
- [ ] The day I excelled an interview
- [ ] The day I had an oral exam
- [ ] The day I got all my credits
- [ ] The day I could go to Japan
- [ ] The day I urgently found a thesis topic
- [ ] The day my resume made a difference
- [ ] The day I submitted my thesis
- [ ] The day I defended my thesis
- [ ] The day I graduated
- [ ] The day it all ended
